modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "vs_collision_damage"
version = "${version}"
displayName = "VS Collision Damage"
authors = "Chelovechic (Github)"
description = '''
Collison damage between ships.
'''
logoFile = "icon.png"

[[dependencies.vs_collision_damage]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.vs_collision_damage]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

#[[dependencies.vs_collision_damage]]
#modId = "architectury"
#mandatory = true
#versionRange = "[9.1.12,)"
#ordering = "AFTER"
#side = "BOTH"

[[dependencies.vs_collision_damage]]
modId = "valkyrienskies"
mandatory = true
versionRange = "[2.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_collision_damage]]
modId = "createbigcannons"
mandatory = true
versionRange = "[5.11.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.vs_collision_damage]]
modId = "towl"
mandatory = false
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
